name: build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - 
        name: Get date (YYYY.MM.dd)
        id: fullDate
        run: echo "::set-output name=fullDate::$(date +'%Y.%m.%d')"
      - 
        name: Get date (YYYY.MM)
        id: yearMonthDate
        run: echo "::set-output name=yearMonthDate::$(date +'%Y.%m')"
      - 
        name: Get date (YYYY)
        id: yearDate
        run: echo "::set-output name=yearDate::$(date +'%Y')"
      -
        name: Dockerhub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Build
        run: |
          docker buildx build \
          --pull \
          --push \
          --platform linux/amd64 \
          --tag mondedie/rutorrent:latest \
          --tag mondedie/rutorrent:${{ steps.fullDate.outputs.fullDate }} \
          --tag mondedie/rutorrent:${{ steps.yearMonthDate.outputs.yearMonthDate }} \
          --tag mondedie/rutorrent:${{ steps.yearDate.outputs.yearDate }} .
          
  filebot:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      -
        name: Dockerhub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Build
        run: |
          docker buildx build \
          --pull \
          --push \
          --build-arg FILEBOT=true \
          --platform linux/amd64 \
          --tag mondedie/rutorrent:filebot .
