name: Docker Build and Push

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.20
    steps:
    - uses: actions/checkout@v2
    - name: Install Docker
      run: |
        apk add --no-cache docker
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker build -t kdtheory/rutorrent:latest .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push kdtheory/rutorrent:latest
