name: Docker Build and Push

on:
  schedule:
    - cron: '0 */6 * * *'  # Vérifie toutes les 6 heures
  workflow_dispatch:  # Permet de déclencher manuellement
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: kdtheory/rutorrent

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for new ruTorrent version
        id: check-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/Novik/ruTorrent/releases/latest | jq -r .tag_name)
          CURRENT_VERSION=$(cat .rutorrent-version 2>/dev/null || echo "")
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ] || [ "${{ github.event_name }}" == "push" ]; then
            echo "New version detected: $LATEST_VERSION"
            echo "$LATEST_VERSION" > .rutorrent-version
            echo "BUILD_NEEDED=true" >> $GITHUB_ENV
            echo "RUTORRENT_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          else
            echo "No new version detected, no build needed"
            echo "BUILD_NEEDED=false" >> $GITHUB_ENV
          fi
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            latest
            type=raw,value={{date 'YYYY.MM.DD'}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
